os: linux
dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

stages:
  - Test
  - Deploy

jobs:
  include:
    - stage: Test
      name: Test site
      script:
        - python -m pip install --upgrade pip
        - pip install -r requirements.txt
        - pip install coveralls
    - stage: Deploy
      name: Unit Tests
      script:
        - echo "yep"